"""
generate_header.py — Convert .tflite binaries to C header arrays for ESP32.

Replicates the xxd -i technique used by TFLite Micro:
    xxd -i model_anomaly.tflite > model_anomaly.h

The generated headers are written directly to
    firmware/main/ai/model_anomaly.h
    firmware/main/ai/model_occupancy.h
    firmware/main/ai/model_forecast.h
    firmware/main/ai/model_appliance.h

Each header exports:
    alignas(8) const uint8_t g_model_<name>[];
    const int                g_model_<name>_len;

Usage:
    python ml/src/generate_header.py \
        --model_dir  ml/models \
        --firmware_dir firmware/main/ai
"""

import argparse
import logging
from pathlib import Path
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

BYTES_PER_LINE = 12

MODELS = [
    "model_anomaly",
    "model_occupancy",
    "model_forecast",
    "model_appliance",
]


def tflite_to_header(tflite_path: Path, header_path: Path,
                      array_name: str) -> None:
    data = tflite_path.read_bytes()
    size = len(data)

    lines = [
        f"// Auto-generated by generate_header.py",
        f"// Source : {tflite_path.name}",
        f"// Size   : {size} bytes ({size / 1024:.1f} KB)",
        f"// Date   : {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"// DO NOT EDIT — regenerate from the TFLite binary.",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// ALIGNED for TFLite Micro flat-buffer access",
        f"alignas(8) const uint8_t {array_name}[] = {{",
    ]

    # Hex bytes formatted as 0xNN, BYTES_PER_LINE per line
    for i in range(0, size, BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        comma   = "," if (i + BYTES_PER_LINE) < size else ""
        lines.append(f"  {hex_str}{comma}")

    lines += [
        "};",
        "",
        f"const int {array_name}_len = {size};",
        "",
    ]

    header_path.write_text("\n".join(lines))
    log.info("  %-30s → %s  (%d bytes)", tflite_path.name,
             header_path.name, size)


def generate_all(model_dir: Path, firmware_dir: Path) -> None:
    firmware_dir.mkdir(parents=True, exist_ok=True)
    generated = 0

    for name in MODELS:
        tflite_path = model_dir / f"{name}.tflite"
        header_path = firmware_dir / f"{name}.h"
        array_name  = f"g_{name}"

        if not tflite_path.exists():
            log.warning("TFLite not found: %s — skipping", tflite_path)
            continue

        tflite_to_header(tflite_path, header_path, array_name)
        generated += 1

    log.info("Generated %d header(s) in %s", generated, firmware_dir)

    if generated > 0:
        # Generate a combined index header
        index_lines = [
            "// TFLite Micro model index — include this to get all models",
            "#pragma once",
            "",
        ]
        for name in MODELS:
            if (firmware_dir / f"{name}.h").exists():
                index_lines.append(f'#include "{name}.h"')
        index_lines.append("")
        (firmware_dir / "models_index.h").write_text("\n".join(index_lines))
        log.info("Index header → models_index.h")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--model_dir",    default="ml/models")
    ap.add_argument("--firmware_dir", default="firmware/main/ai")
    args = ap.parse_args()
    generate_all(Path(args.model_dir), Path(args.firmware_dir))
